name: GA1.13

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Email for commit step"
        required: true
        type: string

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create or Override JSON File
        run: |
          echo "{\"email\": \"${{ inputs.email }}\"}" > "${{ inputs.email }}.json"

      - name: Verify File Exists Before Committing
        run: |
          ls -l "${{ inputs.email }}.json"  # Debug: List file details
          cat "${{ inputs.email }}.json"    # Debug: Print file contents

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "23f2004837@ds.study.iitm.ac.in"
          git add "${{ inputs.email }}.json"
          git commit -m "Updated email file for ${{ inputs.email }}"
          git push

